In [9]:
import numpy as np
import pandas as pd

In [23]:
x = np.array([100, 200, 300, 400, 600,1000, 1200, 1300, 1500, 1700, 1900, 2000]).reshape (-1,1)

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler = MinMaxScaler(feature_range = (1,7))

In [25]:
minMaxNorm = scaler.fit_transform(x)

In [27]:
minMaxNorm

array([[1.        ],
       [1.31578947],
       [1.63157895],
       [1.94736842],
       [2.57894737],
       [3.84210526],
       [4.47368421],
       [4.78947368],
       [5.42105263],
       [6.05263158],
       [6.68421053],
       [7.        ]])

In [29]:
from sklearn.preprocessing import StandardScaler

In [31]:
scaler1= StandardScaler()

In [33]:
zScores = scaler1.fit_transform(x)

In [37]:
zScores

array([[-1.40107496],
       [-1.24823042],
       [-1.09538587],
       [-0.94254133],
       [-0.63685225],
       [-0.02547409],
       [ 0.28021499],
       [ 0.43305953],
       [ 0.73874861],
       [ 1.04443769],
       [ 1.35012678],
       [ 1.50297132]])

In [39]:
maxAbsValue = np.max(np.abs(x))

In [43]:
scaleFactor = 10 ** np.ceil(np.log10(maxAbsValue))

In [51]:
decX = x/scaleFactor
decX

array([[0.01],
       [0.02],
       [0.03],
       [0.04],
       [0.06],
       [0.1 ],
       [0.12],
       [0.13],
       [0.15],
       [0.17],
       [0.19],
       [0.2 ]])

In [87]:
i=0
decX = np.array([])
while i <= len(x)-1:
    decX = np.append(decX, x[i]/10**4)
    i = i + 1
decX

array([0.01, 0.02, 0.03, 0.04, 0.06, 0.1 , 0.12, 0.13, 0.15, 0.17, 0.19,
       0.2 ])

In [90]:
from sklearn.decomposition import PCA

In [100]:
df = pd.read_csv('SurveyData.csv')
x = df.loc[:,:].values

In [102]:
pca = PCA(n_components = 12)

In [112]:
principleComponents = pca.fit_transform(x)

In [114]:
principleDf = pd.DataFrame(data = principleComponents, columns = ['PC1','PC2','PC3','PC4','PC5','PC6','PC7','PC8','PC9','PC10','PC11','PC12'])

In [116]:
principleDf

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12
0,-2.461818,0.264861,-3.748642,-1.752366,3.324363,-1.816123,-1.291766,2.269088,1.007163,3.003777,-1.168778,0.666962
1,-6.319416,8.268149,3.483186,1.805241,0.963229,-0.611808,-0.304384,0.685766,-0.865765,0.236498,0.003873,0.376545
2,-2.584362,0.608395,0.339942,-0.180879,0.752085,0.396326,-1.421424,-0.352922,-0.197131,-0.108656,1.616510,-1.529764
3,-0.757933,1.810996,-1.320100,0.235773,0.357955,-1.591357,-0.143935,-1.236801,0.140541,0.242297,-0.540852,-0.327545
4,1.079370,1.823354,-2.615785,2.433566,-1.131540,0.404940,-0.042040,-0.099361,-0.901307,0.288362,-2.259111,-0.796647
...,...,...,...,...,...,...,...,...,...,...,...,...
308,2.107158,-1.052130,-1.642145,0.188291,-1.052734,-1.562474,-0.046456,-0.776614,1.166805,0.536518,1.214370,0.162620
309,-2.300547,-3.684464,1.027996,-1.402296,-2.366926,-0.838785,1.524055,-0.981450,-0.000222,0.949420,-1.565338,-0.716011
310,0.934393,-2.985025,0.485350,1.891209,0.687916,0.251813,2.060691,0.084377,0.662748,-0.696077,1.131462,0.445991
311,0.878115,-1.962488,0.924628,-1.701478,0.849090,-0.414002,0.668550,0.441419,-0.243481,-1.192101,0.280300,-1.471126
312,3.501283,1.028056,-2.890368,4.912100,-0.800922,-3.548588,2.659171,-0.675465,0.331086,-0.202784,-1.586981,-1.000235

In [120]:
explained_variance = pca.explained_variance_ratio_

variance_df = pd.DataFrame({'Component': [f'PC{i+1}' for i in range(12)],'Explained Variance': explained_variance})

variance_df

   Component  Explained Variance
0        PC1            0.183719
1        PC2            0.134238
2        PC3            0.064745
3        PC4            0.058943
4        PC5            0.050055
5        PC6            0.040766
6        PC7            0.034466
7        PC8            0.026136
8        PC9            0.025877
9       PC10            0.022731
10      PC11            0.021565
11      PC12            0.018183

In [124]:
pca.explained_variance_ratio_

array([0.18371865, 0.13423786, 0.06474489, 0.0589434 , 0.05005509,
       0.04076608, 0.03446637, 0.0261364 , 0.02587716, 0.02273137,
       0.02156538, 0.01818256])